#!/usr/bin/env bash

export AWS_PROFILE=dsp


if command -v dmenu &> /dev/null; then
  CLIENT_NAME=$(echo "" | dmenu -p "Enter client name:" -i  "$@")
else
  notify-send "get-credentials Error" "dmenu not found"
  exit 1
fi

# Exit if user cancelled or provided empty input
if [ -z "$CLIENT_NAME" ]; then
  exit 1
fi

# Fetch the user pool ID for test-dsplatform
USER_POOL_ID=$(aws cognito-idp list-user-pools --max-results 10 --query "UserPools[?Name=='test-dsplatform'].Id" --output text)

if [ -z "$USER_POOL_ID" ]; then
  notify-send "get-credentials Error" "User pool 'test-dsplatform' not found."
  exit 1
fi

# Fetch the client ID for the given client name
CLIENT_ID=$(aws cognito-idp list-user-pool-clients --user-pool-id "$USER_POOL_ID" --query "UserPoolClients[?contains(ClientName, '$CLIENT_NAME')].ClientId" --output text)

if [ -z "$CLIENT_ID" ]; then
  notify-send "get-credentials Error" "Client '$CLIENT_NAME' not found in user pool 'test-dsplatform'."
  exit 1
fi

# Fetch the client secret using the client ID
CLIENT_NAME=$(aws cognito-idp describe-user-pool-client --user-pool-id "$USER_POOL_ID" --client-id "$CLIENT_ID" --query "UserPoolClient.ClientName" --output text)
CLIENT_SECRET=$(aws cognito-idp describe-user-pool-client --user-pool-id "$USER_POOL_ID" --client-id "$CLIENT_ID" --query "UserPoolClient.ClientSecret" --output text)

if [ -z "$CLIENT_SECRET" ]; then
  notify-send "get-credentials Error" "Client secret for '$CLIENT_NAME' not found."
  exit 1
fi

printf "%s\t%s" "$CLIENT_ID" "$CLIENT_SECRET" | xdotool type --clearmodifiers --file -
